### ISSUE TITLE
using lsp for python layer first time, cannot connect to language server

### ISSUE THREAD

**Issue by vv111y** [syl20bnr/spacemacs#10449]
#### Description :octocat:
First time trying out LSP for python. Emacs cannot connect to language server

#### Reproduction guide :beetle:
- installed language python-language-server, pyls-isort, pyls-mypy via pip
- note I am using Anaconda installation.
  - file is located at /Users/Will/anaconda3/lib/python3.6/site-packages

- Start Emacs
- open a python file ```SPC f L .py```

*Observed behaviour:* :eyes: :broken_heart:
- From messages:
    ``` Couldn’t find project root, using the current directory as the root. 
    File mode specification error: (lsp-timed-out-error)
    Error running timer ‘lsp-ui-sideline--run’: (wrong-type-argument hash-table-p nil)
    helm-M-x: No language server is associated with this buffer ```
- ```M-x lsp-capabilities``` results in 'no language server associated with this buffer'
- ```SPC a p``` shows that a python language server process started (2 actually)
- However, shutting down all python processess, closing all .py files, and then trying again results in no process starting.

*Expected behaviour:* :heart: :smile:
- proper connection to language server for lsp functionality

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 5c251f641)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((auto-completion :variables auto-completion-enable-help-tooltip 'manual auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t)
 ansible better-defaults bibtex
 (c-c++ :variables c-c++-enable-clang-support t)
 chrome
 (clojure :variables clojure-enable-fancify-symbols t)
 command-log common-lisp coq cscope csv dash deft docker emacs-lisp erc
 (ess :variables ess-use-auto-complete t ess-use-eldoc t ess-ask-about-transfile nil)
 fasd finance git github go gpu
 (haskell :variables haskell-completion-backend 'intero)
 helm html ibuffer imenu-list ipython-notebook java
 (javascript :variables)
 (latex :variables latex-enable-folding t latex-enable-auto-fill t latex-build-command "LatexMk" latex-enable-magic t)
 lua lsp
 (markdown :variables markdown-live-preview-engine 'vmd)
 nim
 (osx :variables osx-use-option-as-meta t)
 (org :variables org-enable-github-support t org-enable-reveal-js-support t org-enable-bootstrap-support t org-startup-indented t org-startup-folded t)
 pandoc pdf-tools php
 (python :variables python-backend 'lsp)
 racket ranger rust
 (scala :variables scala-auto-insert-asterisk-in-comments t scala-enable-eldoc t scala-indent:use-javadoc-style t)
 scheme search-engine semantic
 (spell-checking :variables spell-checking-enable-by-default nil)
 sql syntax-checking
 (shell :variables shell-default-height 30 shell-default-position 'right)
 themes-megapack tmux
 (treemacs :variables treemacs-use-follow-mode t treemacs-use-filewatch-mode t)
 vagrant version-control yaml zotero)
```
- System configuration features: JPEG RSVG IMAGEMAGICK NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:
```
Debugger entered--Lisp error: (error "Process lsp-python<1> not running")
  process-send-string(#<process lsp-python<1>> "Content-Length: 431
\n
\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":\"file:///Users/Will/DevAcademics/PythonNotebooks/py-kernel.py\",\"languageId\":\"python\",\"version\":0,\"text\":\"#!/usr/bin/env python\\nimport os\\nfrom ipykernel.kernelapp import IPKernelApp\\n\\napp = IPKernelApp.instance()\\napp.initialize([])\\nkernel = app.kernel\\nkernel.shell.push({'print_me': 'Running in previously started kernel.'})\\n\\napp.start()\\n\"}}}")
* lsp--send-no-wait("Content-Length: 431
\n
\n{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/didOpen\",\"params\":{\"textDocument\":{\"uri\":\"file:///Users/Will/DevAcademics/PythonNotebooks/py-kernel.py\",\"languageId\":\"python\",\"version\":0,\"text\":\"#!/usr/bin/env python\\nimport os\\nfrom ipykernel.kernelapp import IPKernelApp\\n\\napp = IPKernelApp.instance()\\napp.initi
```

**Comment by vv111y** [comment]
Also, fwiw ```*lsp-python stderr*``` buffer keeps repeating errors like this:
```
2018-03-07 15:13:48,896 UTC - ERROR - pyls.rpc_manager - synchronous method handler exception for request: <jsonrpc.jsonrpc2.JSONRPC20Request object at 0x114691e10>
Traceback (most recent call last):
  File "/Users/Will/anaconda3/lib/python3.6/site-packages/pyls/rpc_manager.py", line 112, in _handle_request
    maybe_handler = self._message_handler(request.method, request.params if request.params is not None else {})
  File "/Users/Will/anaconda3/lib/python3.6/site-packages/pyls/python_ls.py", line 95, in handle_request
    return getattr(self, method_call)(**params)
  File "/Users/Will/anaconda3/lib/python3.6/site-packages/pyls/python_ls.py", line 243, in m_text_document__hover
    return self.hover(textDocument['uri'], position)
  File "/Users/Will/anaconda3/lib/python3.6/site-packages/pyls/python_ls.py", line 190, in hover
    return self._hook('pyls_hover', doc_uri, position=position) or {'contents': ''}
  File "/Users/Will/anaconda3/lib/python3.6/site-packages/pyls/python_ls.py", line 115, in _hook
    doc = self.workspace.get_document(doc_uri) if doc_uri else None
  File "/Users/Will/anaconda3/lib/python3.6/site-packages/pyls/workspace.py", line 110, in get_document
    return self._docs[doc_uri]
KeyError: 'file:///Users/Will/DevAcademics/PythonNotebooks/py-kernel.py'
```

**Comment by vv111y** [comment]
I'm also getting ```Error running timer ‘lsp-ui-sideline--run’: (wrong-type-argument hash-table-p nil)```
Same error is here https://github.com/emacs-lsp/lsp-haskell/issues/10
But his solution I don't think applies as I have ~/Anaconda3/bin in my exec path. Unless something else is needed.

**Comment by shwsun** [comment]
I am experiencing the same error very recently. Note that the python lsp is working when it was just merged into `develop`.

My setup:
```
Ubuntu
Emacs 27
```

**Comment by shwsun** [comment]
scratch that. https://github.com/emacs-lsp/lsp-mode/issues/336 mentioned that probably need to reinstall lsp and it did solve my problem. 
```
pip uninstall python-language-server   
pip install 'python-language-server[all]'
```

**Comment by shwsun** [comment]
I believe we can close this, it has been a month .... And I believe the lsp backend for python is working properly.

**Comment by syl20bnr** [comment]
👍
