### ISSUE TITLE
Rubocop not working

### ISSUE THREAD

**Issue by rlopzc** [syl20bnr/spacemacs#10507]
#### Description :octocat:
Rubocop is not working.
Branch: develop
Ruby version: 2.5.0

#### Reproduction guide :beetle:
- Start Emacs
- Open a .rb file

*Observed behaviour:* :eyes: :broken_heart:
A window appearns and hides, is from messages buffer:
```
**Messages** buffer:
Ruby: 2.5.0 Gemset: global
Suspicious state from syntax checker ruby-rubocop: Flycheck checker ruby-rubocop returned non-zero exit code 1, but its output contained no errors: /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver.rb:231:in `search_for': Unable to resolve dependency: user requested 'did_you_mean (= 1.2.0)' (Gem::UnsatisfiableDependencyError)
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver.rb:283:in `block in sort_dependencies'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver.rb:277:in `each'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver.rb:277:in `sort_by'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver.rb:277:in `with_index'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver.rb:277:in `sort_dependencies'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:165:in `initial_state'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:106:in `start_resolution'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolution.rb:64:in `resolve'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver/molinillo/lib/molinillo/resolver.rb:42:in `resolve'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/resolver.rb:188:in `resolve'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/request_set.rb:385:in `resolve'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems/request_set.rb:397:in `resolve_current'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:243:in `finish_resolve'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:311:in `block in activate_bin_path'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:309:in `synchronize'
	from /Users/romario/.rvm/rubies/ruby-2.5.0/lib/ruby/2.5.0/rubygems.rb:309:in `activate_bin_path'
	from /Users/romario/.rvm/gems/ruby-2.5.0@global/bin/rubocop:23:in `<main>'
	from /Users/romario/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/romario/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'

Try installing a more recent version of ruby-rubocop, and please open a bug report if the issue persists in the latest release.  Thanks!
```

*Expected behaviour:* :heart: :smile:
Rubocop linting files

#### System Info :computer:
- OS: darwin
- Emacs: 25.3.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 0fa3658c)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: ivy
- Layers:
```elisp
(javascript react restclient auto-completion better-defaults elixir
            (elm :variables elm-sort-imports-on-save t elm-format-on-save t)
            emacs-lisp git github html ivy markdown org osx
            (ranger :variables ranger-show-preview t)
            (ruby :variables ruby-enable-ruby-on-rails-support t ruby-enable-enh-ruby-mode t ruby-version-manager 'rvm)
            ruby-on-rails
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            spell-checking syntax-checking yaml
            (version-control :variables version-control-diff-side 'left)
            (wakatime :variables wakatime-api-key "api_key" wakatime-cli-path "/usr/local/bin/wakatime"))
```
- System configuration features: NOTIFY ACL LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
```
<<BACKTRACE IF RELEVANT>>
```

**Comment by RenWenshan** [comment]
I'd try `gem install rubocop` first and see what happens (make sure `which ruby` returns `/Users/romario/.rvm/rubies/ruby-2.5.0/bin/ruby`).

**Comment by romariolopezc** [comment]
Did that, still not working @RenWenshan , thanks

**Comment by RenWenshan** [comment]
@romariolopezc maybe try "M-x rvm-use" followed up with selecting 2.5.0?

**Comment by romariolopezc** [comment]
@wenshan just tried that, no success :/

On Mar 25, 2018 at 22:49, Wenshan <notifications@github.com> wrote:


@romariolopezc <https://github.com/romariolopezc> maybe try "M-x rvm-use"
followed up with selecting 2.5.0?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/syl20bnr/spacemacs/issues/10507#issuecomment-376045309>,
or mute the thread

**Comment by arubis** [comment]
I experience this without the use of `rvm`.

**Comment by vrinek** [comment]
Me too, not using `rvm`, on Ruby 2.6.0:

```
/Users/kostask/.gem/ruby/2.6.0/gems/rubocop-0.65.0/lib/rubocop/...
```

**Comment by jesusbv** [comment]
> @romariolopezc maybe try "M-x rvm-use" followed up with selecting 2.5.5

It worked for me, installed `rvm` and run `M-x rvm-use` => fixed.
My message was a little bit different 

```
Suspicious state from syntax checker ruby-rubocop: Flycheck checker ruby-rubocop 
returned non-zero exit code 1, but its output contained no errors: 
/home/jesusbv/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/rubygems-bundler-1.4.5/lib/rubygems-bundler/noexec.rb:84:in `setup': undefined method `plain_specs' 
for #<Bundler::RubygemsIntegration:0x000000000286cc28> (NoMethodError)
```
