### ISSUE TITLE
Can't autocomplete function arguments in Python using lsp (also happens using Anaconda)

### ISSUE THREAD

**Issue by augur97** [syl20bnr/spacemacs#10794]
#### Description :octocat:
Can't autocomplete function arguments in Python using lsp (also happens using Anaconda)

#### Reproduction guide :beetle:
- Start Emacs
- Open a Python file
- Try to autocomplete a function parameter

Something like
```python
def main(argument):
    argum
```
and try to autocomplete

*Observed behaviour:* :eyes: :broken_heart:
Cannot autocomplete and the following Message
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/augur/Documentos/programming/python/.#main.py'
```

*Expected behaviour:* :heart: :smile:
Autocompletion popup with argument as option

#### System Info :computer:
- OS: gnu/linux
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 769add7c7)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(helm
 (auto-completion :variables auto-completion-enable-snippets-in-popup t auto-completion-enable-help-tooltip t auto-completion-enable-sort-by-usage t)
 better-defaults emacs-lisp git neotree spell-checking syntax-checking version-control
 (python :variables python-backend 'lsp)
 c-c++ haskell lsp)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 MODULES THREADS LIBSYSTEMD LCMS2

#### Backtrace :paw_prints:
```
Traceback (most recent call last):
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pyls/jsonrpc/endpoint.py", line 113, in consume
    self._handle_request(message['id'], message['method'], message.get('params'))
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pyls/jsonrpc/endpoint.py", line 182, in _handle_request
    handler_result = handler(params)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pyls/jsonrpc/dispatchers.py", line 23, in handler
    return method(**(params or {}))
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pyls/python_ls.py", line 242, in m_text_document__hover
    return self.hover(textDocument['uri'], position)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pyls/python_ls.py", line 189, in hover
    return self._hook('pyls_hover', doc_uri, position=position) or {'contents': ''}
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pyls/python_ls.py", line 113, in _hook
    return hook_handlers(config=self.config, workspace=self.workspace, document=doc, **kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/__init__.py", line 617, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/__init__.py", line 222, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/__init__.py", line 182, in __call__
    return outcome.get_result()
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/callers.py", line 48, in from_call
    result = func()
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/__init__.py", line 180, in <lambda>
    outcome = _Result.from_call(lambda: self.oldcall(hook, hook_impls, kwargs))
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/__init__.py", line 216, in <lambda>
    firstresult=hook.spec_opts.get('firstresult'),
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/callers.py", line 201, in _multicall
    return outcome.get_result()
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/callers.py", line 76, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pluggy/callers.py", line 180, in _multicall
    res = hook_impl.function(*args)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/pyls/plugins/hover.py", line 10, in pyls_hover
    definitions = document.jedi_script(position).goto_definitions()
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/api/__init__.py", line 197, in goto_definitions
    definitions = helpers.evaluate_goto_definition(self._evaluator, context, leaf)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/api/helpers.py", line 189, in evaluate_goto_definition
    return evaluator.goto_definitions(context, leaf)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 234, in goto_definitions
    return helpers.evaluate_call_of_leaf(context, name)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/helpers.py", line 99, in evaluate_call_of_leaf
    values = context.eval_node(base)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 139, in eval_node
    return self.evaluator.eval_element(self, node)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 194, in eval_element
    return self._eval_element_if_evaluated(context, element)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 206, in _eval_element_if_evaluated
    return self._eval_element_cached(context, element)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/__init__.py", line 210, in _eval_element_cached
    return eval_node(context, element)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 48, in wrapper
    return func(context, *args, **kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 72, in eval_node
    return eval_atom(context, element)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/syntax_tree.py", line 208, in eval_atom
    search_global=True
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/_compatibility.py", line 264, in <lambda>
    return lambda *args, **kwargs: self.func(obj, *args, **kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/base_context.py", line 156, in py__getattribute__
    return f.find(filters, attribute_lookup=not search_global)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 67, in find
    types = self._names_to_types(names, attribute_lookup)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 178, in _names_to_types
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/common/context.py", line 34, in from_sets
    sets = list(sets)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/finder.py", line 178, in <genexpr>
    contexts = ContextSet.from_sets(name.infer() for name in names)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 142, in infer
    return self.get_param().infer()
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/filters.py", line 145, in get_param
    params = self.parent_context.get_params()
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/context/function.py", line 244, in get_params
    return self.var_args.get_params(self)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/arguments.py", line 82, in get_params
    execution_context.tree_node
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/debug.py", line 79, in wrapper
    return func(*args, **kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/dynamic.py", line 90, in search_params
    string_name=string_name,
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/cache.py", line 40, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/utils.py", line 20, in wrapper
    return list(func(*args, **kwargs))
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/dynamic.py", line 124, in _search_function_executions
    evaluator, [module_context], string_name):
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/imports.py", line 569, in get_modules_containing_name
    m = check_fs(p)
  File "/home/augur/.pyenv/versions/3.6.5/lib/python3.6/site-packages/jedi/evaluate/imports.py", line 536, in check_fs
    with open(path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/augur/Documentos/programming/python/.#main.py'
```

**Comment by augur97** [comment]
I was able to solve it thanks to [this issue from odoo](https://github.com/odoo/odoo/issues/21214) adding  
```lisp
  (setq create-lockfiles nil)
```
to my user config

It seems to be a problem with emacs lockfiles and disabling them seems to be a valid workaround
