### ISSUE TITLE
Develop Branch Java layer, with Meghanada server, not working

### ISSUE THREAD

**Issue by dmsilver2** [syl20bnr/spacemacs#12006]
#### Description :octocat:
On Develop branch the Meghanada java layer is not working as expected.  There are 3 issues.
1) When I go into a java file for the first time the java layer is not automatically installed. I had to manaully go into .spacemacs file to add the layer.
2) The java layer default is not installing the Meghanada server. Again I had to manually do this.
3) After manually downloading the Meghanada server .jar file and placing it within the ~/.emacs.d/.cache/meghanada directory. The Meghanada server does not start up.  The Meghanada server is displayed as disconnected. The meghanada error cannot find "mvn"; however, maven is installed on my machine and I can call it within commandline.

#### Reproduction guide :beetle:
- clone the develop branch
- remove or rename you .spacemacs file (if you have one) so a fresh instance will be made
- open spacemacs
- go to a *.java file within a maven project

*Observed behaviour:* :eyes: :broken_heart:
The java layer is not working as intended

*Expected behaviour:* :heart: :smile:
Java layer should install itself when you enter a java file for the first time.  It should also install the default Meghanada mode's server.  Lastly the client should be connected to the meghanada server

#### System Info :computer:
- OS: windows-nt
- Emacs: 26.1
- Spacemacs: 0.300.0
- Spacemacs branch: develop (rev. 4b195ddfc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
((java :variables java-backend 'meghanada)
 helm emacs-lisp multiple-cursors treemacs
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 syntax-checking version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS THREADS LCMS2

#### Backtrace :paw_prints:
```
[2019-02-20 18:49:23,559][INFO ][MavenProje:  76] running maven. build classpath ...
[2019-02-20 18:49:23,570][INFO ][MavenProje: 175] run mvn: mvn dependency:build-classpath -Dmdep.outputFile=C:\Users\Daniel Silver\AppData\Local\Temp\meghanada-maven-classpath3976390800527221304.log
[2019-02-20 18:49:23,577][ERROR][EmacsServe: 385] Catching
meghanada.project.ProjectParseException: java.io.IOException: Cannot run program "mvn" (in directory "C:\Users\Daniel Silver\eclipse-workspace\artifact"): CreateProcess error=2, The system cannot find the file specified
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:152) ~[meghanada-1.0.12.jar:?]
	at meghanada.session.Session.loadProject(Session.java:206) ~[meghanada-1.0.12.jar:?]
	at meghanada.session.Session.findProject(Session.java:133) ~[meghanada-1.0.12.jar:?]
	at meghanada.session.Session.createSession(Session.java:103) ~[meghanada-1.0.12.jar:?]
	at meghanada.session.Session.createSession(Session.java:98) ~[meghanada-1.0.12.jar:?]
	at meghanada.server.emacs.EmacsServer.startServer(EmacsServer.java:379) [meghanada-1.0.12.jar:?]
	at meghanada.Main.main(Main.java:134) [meghanada-1.0.12.jar:?]
Caused by: java.io.IOException: Cannot run program "mvn" (in directory "C:\Users\Daniel Silver\eclipse-workspace\artifact"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048) ~[?:1.8.0_201]
	at meghanada.project.maven.MavenProject.runMvn(MavenProject.java:178) ~[meghanada-1.0.12.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:91) ~[meghanada-1.0.12.jar:?]
	... 6 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method) ~[?:1.8.0_201]
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:386) ~[?:1.8.0_201]
	at java.lang.ProcessImpl.start(ProcessImpl.java:137) ~[?:1.8.0_201]
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029) ~[?:1.8.0_201]
	at meghanada.project.maven.MavenProject.runMvn(MavenProject.java:178) ~[meghanada-1.0.12.jar:?]
	at meghanada.project.maven.MavenProject.parseProject(MavenProject.java:91) ~[meghanada-1.0.12.jar:?]
```

**Comment by Compro-Prasad** [comment]
From the backtrace I can see that you don't have mvn installed.

**Comment by dmsilver2** [comment]
I do have it installed

λ mvn -version
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-24T13:41:47-05:00)
Maven home: C:\apache-maven-3.6.0
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Compro-Prasad** [comment]
Maybe your PATH isn't properly set?

**Comment by dmsilver2** [comment]
If my path was incorrectly set then I would not be able to call mvn command in the first place.  

Below is my Path variable echoed from command line.

C:\>echo %path:;=&echo.%
C:\Program Files\Java\jdk1.8.0_201\bin
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\
C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\
C:\Windows\system32
C:\Windows
C:\Windows\System32\Wbem
C:\Windows\System32\WindowsPowerShell\v1.0\
C:\Windows\System32\OpenSSH\
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files\Intel\Intel(R) Management Engine Components\DAL
C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files\Intel\Intel(R) Management Engine Components\IPT
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\Git\cmd
C:\apache-maven-3.6.0\bin
C:\Program Files\nodejs\
C:\emacs-26.1-x86_64\bin
C:\Program Files (x86)\Brackets\command
C:\Users\dsilver\AppData\Local\Microsoft\WindowsApps
C:\Users\dsilver\AppData\Roaming\npm

**Comment by Compro-Prasad** [comment]
@dmsilver2 Did you try running(checking) it from Emacs or outside Emacs?

**Comment by dmsilver2** [comment]
I can call the mvn command within emacs (shell command) and outside emacs (within windows command).

@Compro-Prasad Did you tried to reproduce my spacemacs errors?  And do you encounter the same errors or not?

**Comment by Compro-Prasad** [comment]
@dmsilver2 I don't use Windows.

**Comment by beyondpie** [comment]
Maybe you cannot use 'mvn' in Emacs? I know that Emacs has the different env not exactly following the PATH env. 
My suggestion is try to run in your terminal with `mvn install` like command to firstly build the project by your self. Then from my experience, `meghanada` will recognize the indexes it needs.

**Comment by thegeorgeous** [comment]
Meghanada works for me but it does not have the shortcuts mentioned in the development branch.
