### ISSUE TITLE
Python layer gives warning on startup 

### ISSUE THREAD

**Issue by vikke1234** [syl20bnr/spacemacs#12060]
#### Description :octocat:
Python layer gives an error each time on startup, when I tried submitting from spacemacs it just said C-c C-c undefined

#### Reproduction guide :beetle:
- Start Emacs
- Gives the error, for some reason it look at a c++ file and crashes it seems
*Observed behaviour:* :eyes: :broken_heart:
Well it just makes a small buffer where the stack trace below is shown

*Expected behaviour:* :heart: :smile:
That it doesn't give the error I guess

#### System Info :computer:
- OS: gnu/linux
- Emacs: 25.2.2
- Spacemacs: 0.200.13
- Spacemacs branch: master (rev. c7a103a77)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python html helm auto-completion emacs-lisp c-c++ semantic
        (shell :variables shell-default-height 30 shell-default-position 'bottom)
        syntax-checking git version-control)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG IMAGEMAGICK SOUND GPM DBUS GSETTINGS NOTIFY ACL LIBSELINUX GNUTLS LIBXML2 FREETYPE M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11

#### Backtrace :paw_prints:
```
Error (use-package): python/:init: Invalid version syntax: ‘Exception AttributeError: "'module' object has no attribute 'isgenerator'" in <module 'inspect' from '/usr/lib/python2.7/inspect.pyc'> ignored
/usr/lib/python2.7/dist-packages/bs4/builder/_lxml.py:11: RuntimeWarning: Cython module failed to patch module with custom type
  from lxml import etree
/* ASL - Arithmetic Shift Left*/
case 0x69: 
case 0x65: 
case 0x75: 
case 0x6D: 
case 0x7D: 
case 0x79: 
case 0x61: 
case 0x71: 
	break;
/* BCS - Branch if Carry Set*/
case 0x29: 
case 0x25: 
case 0x35: 
case 0x2D: 
case 0x3D: 
case 0x39: 
case 0x21: 
case 0x31: 
	break;
/* BIT - Bit Test*/
case 0x0A: 
case 0x06: 
case 0x16: 
case 0x0E: 
case 0x1E: 
	break;
/* BNE - Branch if Not Equal*/
case 0x90: 
	break;
/* BRK - Force Interrupt*/
case 0xB0: 
	break;
/* BVS - Branch if Overflow Set*/
case 0xF0: 
	break;
/* CLD - Clear Decimal Mode*/
case 0x24: 
case 0x2C: 
	break;
/* CLV - Clear Overflow Flag*/
case 0x30: 
	break;
/* CPX - Compare X Register*/
case 0xD0: 
	break;
/* DEC - Decrement Memory*/
case 0x10: 
	break;
/* DEY - Decrement Y Register*/
case 0x00: 
	break;
/* INC - Increment Memory*/
case 0x50: 
	break;
/* INY - Increment Y Register*/
case 0x70: 
	break;
/* JSR - Jump to Subroutine*/
case 0x18: 
	break;
/* LDX - Load X Register*/
case 0xD8: 
	break;
/* LSR - Logical Shift Right*/
case 0x58: 
	break;
/* ORA - Logical Inclusive OR*/
case 0xB8: 
	break;
/* PHP - Push Processor Status*/
case 0xC9: 
case 0xC5: 
case 0xD5: 
case 0xCD: 
case 0xDD: 
case 0xD9: 
case 0xC1: 
case 0xD1: 
	break;
/* PLP - Pull Processor Status*/
case 0xE0: 
case 0xE4: 
case 0xEC: 
	break;
/* ROR - Rotate Right*/
case 0xC0: 
case 0xC4: 
case 0xCC: 
	break;
/* RTS - Return from Subroutine*/
case 0xC6: 
case 0xD6: 
case 0xCE: 
case 0xDE: 
	break;
/* SEC - Set Carry Flag*/
case 0xCA: 
	break;
/* SEI - Set Interrupt Disable*/
case 0x88: 
	break;
/* STX - Store X Register*/
case 0x49: 
case 0x45: 
case 0x55: 
case 0x4D: 
case 0x5D: 
case 0x59: 
case 0x41: 
case 0x51: 
	break;
/* TAX - Transfer Accumulator to X*/
case 0xE6: 
case 0xF6: 
case 0xEE: 
case 0xFE: 
	break;
/* TSX - Transfer Stack Pointer to X*/
case 0xE8: 
	break;
/* TXS - Transfer X to Stack Pointer*/
case 0xC8: 
	break;
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/IPython/__init__.py", line 48, in <module>
    from .core.application import Application
  File "/usr/lib/python2.7/dist-packages/IPython/core/application.py", line 23, in <module>
    from traitlets.config.application import Application, catch_config_error
  File "/usr/lib/python2.7/dist-packages/traitlets/__init__.py", line 1, in <module>
    from .traitlets import *
  File "/usr/lib/python2.7/dist-packages/traitlets/traitlets.py", line 44, in <module>
    import inspect
  File "/usr/lib/python2.7/inspect.py", line 37, in <module>
    import dis
  File "/usr/lib/python2.7/dis.py", line 7, in <module>
    from opcode import __all__ as _opcodes_all
ImportError: cannot import name __all__’ (must start with a number)
```

**Comment by vikke1234** [comment]
seems like it's an lxml issue, happens when I try to import etree from lxml in a normal python environment

**Comment by beyondpie** [comment]
Should be the problem of your python, not Emacs/Spacemacs.
Try to reinstall python or how about find this file named inspect.pyc, and delete it.
