### ISSUE TITLE
anaconda mode keyerror

### ISSUE THREAD

**Issue by normrubin** [syl20bnr/spacemacs#12746]
II just installed spacemacs for the first time (win 10 ) and opened a python file 
I  got an error in  the *anaconda-mode buffer 

does this mean that my install failed?  How would i fix this

anaconda_mode port 63651
127.0.0.1 - - [19/Sep/2019 11:42:28] ================================================================================
Traceback (most recent call last):
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\cache.py", line 141, in wrapper
    return dct[key]
KeyError: ((), frozenset({('resolve_stars', True)}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\service_factory-0.1.5-py3.7.egg\service_factory\service.py", line 101, in apply
    result = method(**params)
  File "<string>", line 98, in wrapper
  File "<string>", line 130, in company_complete
  File "<string>", line 130, in <listcomp>
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\api\classes.py", line 479, in docstring
    return super(Completion, self).docstring(raw=raw, fast=fast)
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\api\classes.py", line 242, in docstring
    return _Help(self._name).docstring(fast=fast, raw=raw)
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\api\classes.py", line 756, in docstring
    signature_text = _format_signatures(context)
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\api\classes.py", line 715, in _format_signatures
    for signature in context.get_signatures()
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\api\classes.py", line 715, in <genexpr>
    for signature in context.get_signatures()
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\evaluate\signature.py", line 28, in to_string
    s = self.name.string_name + '(' + ', '.join(param_strings()) + ')'
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\evaluate\signature.py", line 10, in param_strings
    for n in self.get_param_names(resolve_stars=True):
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\cache.py", line 143, in wrapper
    result = method(self, *args, **kwargs)
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\evaluate\signature.py", line 89, in get_param_names
    params = process_params(params)
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\evaluate\utils.py", line 20, in wrapper
    return list(func(*args, **kwargs))
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\evaluate\star_args.py", line 135, in process_params
    for func_and_argument in arg_callables:
  File "C:\Users\norm/.emacs.d/.cache/anaconda-mode/0.1.13\jedi-0.15.1-py3.7.egg\jedi\evaluate\star_args.py", line 51, in _iter_nodes_for_param
    assert False
AssertionError

**Comment by Compro-Prasad** [comment]
To be precise `anaconda-mode` is no longer being maintained actively. You should switch to `lsp-mode`.

**Comment by normrubin** [comment]
I added 
 (python :variables python-backend 'lsp)  to my .spacemacs file  opened a python file and typed
np.  but this still started anaconda-mode -  what else do i need to do to switch?

i did trace down this error a little and found that the rpc call to jedi was failing with a generic 500 error which suggests to me that there is some kind of version mismatch

I'm kind of surprised that the spacemacs  python does not work out of the box.

**Comment by Compro-Prasad** [comment]
Python does work for me. I used `anaconda-mode` before. It worked well for me. It was a pain to setup virtualenvs until I got to know `pipenv` properly. Then I switched to `lsp-mode` and `pipenv` which required zero config from my side.

**Comment by normrubin** [comment]
I'd find it a help if you let me know how you set it up,  exactly what is
in your .spacemacs file to switch to lsp-mode?

eventually i'd like to use conta environments but i thought one step at a
time

**Comment by Compro-Prasad** [comment]
https://github.com/Compro-Prasad/.spacemacs.d/blob/master/init.el

**Comment by Compro-Prasad** [comment]
You will also need to install `python-language-server` through `pip` and hope that Emacs will automatically recognize it. You should also be using `develop` branch.
