### ISSUE TITLE
Having rouble starting the Java layer with Meghanada

### ISSUE THREAD

**Issue by Sammyalhashe** [syl20bnr/spacemacs#13173]
I am new to spacemacs, so I apologize in advance for any silly lapses in judgement. I am using the following configuration:

```lisp
dotspacemacs-configuration-layers
   '(
     python
     (java :variables java-backend 'meghanada)
     ;; ----------------------------------------------------------------
     ;; Example of useful layers you may want to use right away.
     ;; Uncomment some layer names and press <SPC f e R> (Vim style) or
     ;; <M-m f e R> (Emacs style) to install them.
     ;; ----------------------------------------------------------------
     helm
     auto-completion
     better-defaults
     emacs-lisp
     git
     markdown
     lsp
     org
     ;; (shell :variables
     ;;        shell-default-height 30
     ;;        shell-default-position 'bottom)
     ;; spell-checking
     syntax-checking
     ;; version-control
     )
   ;; List of additional packages that will be installed without being
   ;; wrapped in a layer. If you need some configuration for these
   ;; packages, then consider creating a layer. You can also put the
   ;; configuration in `dotspacemacs/user-config'.
   dotspacemacs-additional-packages '()
   ;; A list of packages that cannot be updated.
   dotspacemacs-frozen-packages '()
   ;; A list of packages that will not be installed and loaded.
   dotspacemacs-excluded-packages '()
   ;; Defines the behaviour of Spacemacs when installing packages.
   ;; Possible values are `used-only', `used-but-keep-unused' and `all'.
   ;; `used-only' installs only explicitly used packages and uninstall any
   ;; unused packages as well as their unused dependencies.
   ;; `used-but-keep-unused' installs only the used packages but won't uninstall
   ;; them if they become unused. `all' installs *all* packages supported by
   ;; Spacemacs and never uninstall them. (default is `used-only')
   dotspacemacs-install-packages 'used-only))

```
When I open a java file/project, the Meghanada server seems to start normally (indexing the project and such), but then I get the following error message. This is probably me just missing something very small, but I have drawn blanks and have gone over https://develop.spacemacs.org/layers/+lang/java/README.html a good chunk of times. 
```
[INFO ][Main      :  55] use java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/jre
[INFO ][Main      :  56] use java runtime: Java(TM) SE Runtime Environment 1.8.0_172-b11
[INFO ][Main      :  60] use java vm: Java HotSpot(TM) 64-Bit Server VM 25.172-b11
[INFO ][ClassPathU:  26] add tools.jar path:/Library/Java/JavaVirtualMachines/jdk1.8.0_172.jdk/Contents/Home/lib/tools.jar
[INFO ][Session   : 194] load project from cache. projectRoot:/Users/sammyalhashemi/Documents/Scheduler
[INFO ][EmacsServe: 364] zpage tracez handler http://localhost:53893/tracez
[INFO ][CacheEvent:  75] start analyze sources ...
[INFO ][CacheEvent: 101] class index size:0 total elapsed:9.285 ms
[INFO ][CacheEvent: 106] Ready
[INFO ][EmacsServe: 370] Start server Listen localhost port:53894
[INFO ][EmacsServe: 391] client connected
[INFO ][CacheEvent:  68] create class index ... read 0 jars. elapsed:2.366 s
[WARN ][JavaSource:  75] source cache miss /Users/sammyalhashemi/Documents/Scheduler/src/main/java/com/Scheduler/CriticalPath/CriticalPath.java
[ERROR][JavaComple:1202] Catching
meghanada.com.google.common.util.concurrent.ExecutionError: com.sun.tools.javac.util.Abort
	at meghanada.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049) ~[meghanada-1.2.1.jar:?]
	at meghanada.com.google.common.cache.LocalCache.get(LocalCache.java:3953) ~[meghanada-1.2.1.jar:?]
	at meghanada.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3976) ~[meghanada-1.2.1.jar:?]
	at meghanada.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4960) ~[meghanada-1.2.1.jar:?]
	at meghanada.cache.GlobalCache.getSource(GlobalCache.java:165) ~[meghanada-1.2.1.jar:?]
	at meghanada.completion.JavaCompletion.getSource(JavaCompletion.java:1141) ~[meghanada-1.2.1.jar:?]
	at meghanada.completion.JavaCompletion.completionAtInternal(JavaCompletion.java:1187) ~[meghanada-1.2.1.jar:?]
	at meghanada.completion.JavaCompletion.completionAt(JavaCompletion.java:1160) ~[meghanada-1.2.1.jar:?]
	at meghanada.session.Session.completionAt(Session.java:465) ~[meghanada-1.2.1.jar:?]
	at meghanada.server.CommandHandler.autocomplete(CommandHandler.java:187) ~[meghanada-1.2.1.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$dispatch$2(EmacsServer.java:93) ~[meghanada-1.2.1.jar:?]
	at com.leacox.motif.matching.Matching1.lambda$get$15(Matching1.java:45) ~[meghanada-1.2.1.jar:?]
	at com.leacox.motif.matching.Pattern$1.apply(Pattern.java:40) ~[meghanada-1.2.1.jar:?]
	at com.leacox.motif.matching.FluentMatchingR.getMatch(FluentMatchingR.java:118) ~[meghanada-1.2.1.jar:?]
	at meghanada.server.emacs.EmacsServer.dispatch(EmacsServer.java:350) ~[meghanada-1.2.1.jar:?]
	at meghanada.server.emacs.EmacsServer.lambda$acceptConnection$35(EmacsServer.java:436) ~[meghanada-1.2.1.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_172]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_172]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
```

**Comment by Trapez** [comment]
See if it works on java 11.

**Comment by Sammyalhashe** [comment]
Again, apologies for a newbie question, but how do I configure which version on Java Soacemacs works with? Does it just inherit from JAVA_HOME?

**Comment by Trapez** [comment]
Some info here on ways to switch between java versions on OSX.
https://stackoverflow.com/questions/52524112/how-do-i-install-java-on-mac-osx-allowing-version-switching

**Comment by Sammyalhashe** [comment]
I'm able to switch, but it uses the same version everytime I open a Java file.

**Comment by Trapez** [comment]
You need to run emacs from the terminal. Any switch based on JAVA_HOME only applies there.
Have you tried the lsp backend instead of meghanada?

**Comment by Sammyalhashe** [comment]
Apologies for the late reply, I get the following error when I try with lsp. 
<img width="818" alt="Screen Shot 2020-01-16 at 11 22 31 PM" src="https://user-images.githubusercontent.com/20797997/72584217-35bd7200-38b7-11ea-8e6f-4cab485109a7.png">

**Comment by Sammyalhashe** [comment]
Closing as this seems to be an issue with lsp-java. https://github.com/emacs-lsp/lsp-java/issues/188
