### ISSUE TITLE
anaconda-mode got errors.

### ISSUE THREAD

**Issue by zentorwie** [syl20bnr/spacemacs#4646]
I was writing python3 code and used `pyvenv-workon`.

When writing codes I got a short but significant pause, and the minibuffer showed some errors.

The \*Messages\* buffer:
```
Loading /home/zentorwie/.emacs.d/core/core-load-paths.el (source)...done
Loading /home/zentorwie/.spacemacs...done
Loading /home/zentorwie/.emacs.d/.cache/spacemacs-buffer.el (source)...done
Open the quickhelp.
Loading /home/zentorwie/.emacs.d/layers/+distribution/spacemacs/config.el (source)...
Loading /home/zentorwie/.emacs.d/layers/+distribution/spacemacs-base/funcs.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+distribution/spacemacs-base/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+distribution/spacemacs-base/keybindings.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+window-management/spacemacs-layouts/funcs.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+window-management/spacemacs-layouts/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+distribution/spacemacs/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/auto-completion/funcs.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/auto-completion/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/better-defaults/funcs.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/better-defaults/keybindings.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+lang/emacs-lisp/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+source-control/git/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+lang/markdown/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/org/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+frameworks/django/config.el (source)...
Loading /home/zentorwie/.emacs.d/layers/+lang/python/funcs.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+lang/python/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+frameworks/django/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+source-control/version-control/funcs.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+source-control/version-control/config.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+source-control/version-control/keybindings.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+lang/python/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+lang/python/extensions.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+window-management/spacemacs-layouts/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+distribution/spacemacs-base/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+distribution/spacemacs/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/auto-completion/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+lang/emacs-lisp/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+source-control/git/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+lang/markdown/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/org/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/org/extensions.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+frameworks/django/packages.el (source)...done
Loading /home/zentorwie/.emacs.d/layers/+source-control/version-control/packages.el (source)...done
You appear to be setting environment variables ("PATH" "MANPATH") in your .bashrc or .zshrc: those files are only read by interactive shells, so you should instead set environment variables in startup files like .profile, .bash_profile or .zshenv.  Refer to your shell's man page for more info.  Customize `exec-path-from-shell-arguments' to remove "-i" when done, or disable `exec-path-from-shell-check-startup-files' to disable this message.
Spacemacs is ready.
Start checking for new version...
Loading /home/zentorwie/.emacs.d/.cache/recentf...done
Open the quickhelp.
Spacemacs is up to date.
s is undefined
user-error: Can't find 
Buffer is read-only: #<buffer *spacemacs*>
[yas] Prepared just-in-time loading for /home/zentorwie/.emacs.d/layers/auto-completion/snippets
[yas] Discovered there was already  *code-conversion-work* in fundamental-mode
[yas] Discovered there was already  *Echo Area 0* in fundamental-mode
[yas] Discovered there was already  *Echo Area 1* in fundamental-mode
[yas] Discovered there was already  *which-key* in fundamental-mode
[yas] Discovered there was already app.py in python-mode
[yas] Discovered there was already *scratch* in text-mode
[yas] Loading for `text-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/text-mode) (quote text-mode)))!
[yas] Loading snippet files from /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/text-mode
[yas] Loading for `fundamental-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/fundamental-mode) (quote fundamental-mode)))!
[yas] Loading snippet files from /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/fundamental-mode
Loading /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/fundamental-mode/.yas-setup...done
[yas] Loading for `python-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/python-mode) (quote python-mode)))!
[yas] Loading snippet files from /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/python-mode
Loading /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/python-mode/.yas-setup...done
[yas] Loading for `prog-mode', just-in-time: (lambda nil (yas--load-directory-1 (quote /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/prog-mode) (quote prog-mode)))!
[yas] Loading snippet files from /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/prog-mode
Loading /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets/prog-mode/.yas-setup...done
[yas] Prepared just-in-time loading for /home/zentorwie/.emacs.d/elpa/yasnippet-20160104.129/snippets
[yas] Prepared just-in-time loading for /home/zentorwie/.emacs.d/private/snippets/
[yas] Reloaded everything (snippets will load just-in-time)....
Skip anaconda-mode complete response
Auto-saving...done
Quit [2 times]
Search failed. This means there is unmatched expression somewhere or we are at the beginning/end of file. [2 times]
python-completion-complete-at-point: Completion needs an inferior Python process running
eldoc error: (error 127.0.0.1%3anil/80 Name or service not known)
Skip anaconda-mode complete response
Skip anaconda-mode eldoc response
error in process filter: apply: Wrong type argument: stringp, ((message . "Server error") (data . "StopIteration()") (code . -32000))
error in process filter: Wrong type argument: stringp, ((message . "Server error") (data . "StopIteration()") (code . -32000))
error in process filter: apply: Wrong type argument: stringp, ((message . "Server error") (data . "StopIteration()") (code . -32000))
error in process filter: Wrong type argument: stringp, ((message . "Server error") (data . "StopIteration()") (code . -32000))
error in process filter: apply: Wrong type argument: stringp, ((message . "Server error") (data . "StopIteration()") (code . -32000))
error in process filter: Wrong type argument: stringp, ((message . "Server error") (data . "StopIteration()") (code . -32000))
g g
byte-code: Beginning of buffer [3 times]
g g
```

The \*anaconda-mode\* buffer:
```
anaconda_mode port 9000

Process anaconda-mode killed
anaconda_mode port 9000
127.0.0.1 - - [17/Jan/2016 17:57:15] ================================================================================
Traceback (most recent call last):
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 100, in apply
    result = method(**params)
  File "anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "anaconda_mode.py", line 59, in complete
    return script.completions()
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/finder.py", line 280, in _name_to_types
    types += evaluator.eval_element(typ.node_from_name(name))
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 239, in _eval_atom
    return self.eval_element(c[1])
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/precedence.py", line 45, in calculate_children
    right = next(iterator)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "<string>", line 2, in raise_from
service_factory.exceptions.ServiceException: (500, '{"error": {"code": -32000, "data": "StopIteration()", "message": "Server error"}, "jsonrpc": "2.0", "id": 1}')
127.0.0.1 - - [17/Jan/2016 17:57:17] ================================================================================
Traceback (most recent call last):
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 100, in apply
    result = method(**params)
  File "anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "anaconda_mode.py", line 59, in complete
    return script.completions()
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/finder.py", line 280, in _name_to_types
    types += evaluator.eval_element(typ.node_from_name(name))
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 239, in _eval_atom
    return self.eval_element(c[1])
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/precedence.py", line 45, in calculate_children
    right = next(iterator)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "<string>", line 2, in raise_from
service_factory.exceptions.ServiceException: (500, '{"error": {"code": -32000, "data": "StopIteration()", "message": "Server error"}, "jsonrpc": "2.0", "id": 1}')
127.0.0.1 - - [17/Jan/2016 17:57:19] ================================================================================
Traceback (most recent call last):
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 100, in apply
    result = method(**params)
  File "anaconda_mode.py", line 27, in wrapper
    return f(Script(source, line, column, path))
  File "anaconda_mode.py", line 49, in wrapper
    for definition in f(script)]
  File "anaconda_mode.py", line 59, in complete
    return script.completions()
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 188, in completions
    completion_names = get_completions(user_stmt, b)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 174, in get_completions
    completion_names += self._simple_complete(path, dot, like)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 250, in _simple_complete
    scopes = list(self._prepare_goto(path, True))
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/api/__init__.py", line 294, in _prepare_goto
    scopes = self._evaluator.eval_element(eval_stmt)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 230, in _eval_atom
    return self.find_types(scope, atom, stmt.start_pos, search_global=True)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 120, in find_types
    return f.find(scopes, search_global)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/debug.py", line 52, in wrapper
    result = func(*args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/finder.py", line 87, in find
    types = self._names_to_types(names, search_global)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/finder.py", line 233, in _names_to_types
    new_types = _name_to_types(self._evaluator, name, self.scope)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/finder.py", line 280, in _name_to_types
    types += evaluator.eval_element(typ.node_from_name(name))
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 169, in eval_element
    return self._eval_atom(element)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 239, in _eval_atom
    return self.eval_element(c[1])
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/cache.py", line 41, in wrapper
    rv = function(obj, *args, **kwargs)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/__init__.py", line 212, in eval_element
    return precedence.calculate_children(self, element.children)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/jedi/evaluate/precedence.py", line 45, in calculate_children
    right = next(iterator)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/zentorwie/.emacs.d/.cache/anaconda-mode/0.1.1/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "<string>", line 2, in raise_from
service_factory.exceptions.ServiceException: (500, '{"error": {"code": -32000, "data": "StopIteration()", "message": "Server error"}, "jsonrpc": "2.0", "id": 1}')
```

**Comment by zentorwie** [comment]
Environment:
OS: Ubuntu 14.04 LTS
Emacs: 24.5
Spacemacs version: 0.105.8
Virtualenv python version: 3.4.3

**Comment by zentorwie** [comment]
The code I was writing when errors occured:
```
@asyncio.coroutine
def select(sql, args, size=None):
    log(sql, args)
    global __pool
    with (yield from __pool) as conn:
        cur = yield from conn.cursor(aiomysql.DictCursor)
# ......
```
Errors occured when I typed "conn.cur"

**Comment by cpaulik** [comment]
This seems like a `jedi` or `anaconda` problem. So please raise it there.

Are you sure you are using `yield` correctly here? I got rid of the error message when replacing yield by some other variable name.
