### ISSUE TITLE
python completion doesn't work with company-anaconda

### ISSUE THREAD

**Issue by LiVincent-Zhang** [syl20bnr/spacemacs#6143]
I install default python layer and auto-complete layer. When I open an python buffer, and press TAB to complete something, the spacemacs give warning
```
Completion needs an inferior Python process running 
```
Then I open an python interpreter with `C-c C-p` and TAB again. The result is always 
```
[No matches]
```
It is strange that some modules can give properly candidates for completion. such as `os` or `sys`, but `argparse` can not. Is this a bug or just my configuration is broken?

**Comment by LiVincent-Zhang** [comment]
After I add company-jedi to python layer, the auto-completion work fine, but it can't jump to definition anyway. Is there any solution?

**Comment by cpaulik** [comment]
There should be no need for you to press `TAB` autocompletion should appear as you type. What does your `*anaconda-mode*` buffer say?

**Comment by LiVincent-Zhang** [comment]
@cpaulik yes, after I installed the company-jedi, TAB is needless, but before that, there is nothing happen as I type. I haven't change anything of spacemacs configuration.

**Comment by LiVincent-Zhang** [comment]
@cpaulik This is what in my `*anaconda-mode*` buffer.

```
Collecting anaconda-mode==0.1.1
Collecting jedi>=0.9.0 (from anaconda-mode==0.1.1)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting service-factory>=0.1.2 (from anaconda-mode==0.1.1)
Collecting six (from service-factory>=0.1.2->anaconda-mode==0.1.1)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: jedi, six, service-factory, anaconda-mode
[31mException:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 317, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 835, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 1030, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python2.7/site-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/local/lib/python2.7/site-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/command/install.py", line 264, in finalize_options
    "must supply either home or prefix/exec-prefix -- not both"
DistutilsOptionError: must supply either home or prefix/exec-prefix -- not both[0m
[33mYou are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.[0m
[0;31mOut[[1;31m1[0;31m]: [0m2
[TerminalIPythonApp] WARNING | File not found: u'anaconda_mode.py'

```

**Comment by LiVincent-Zhang** [comment]
Solved! Thanks to @cpaulik. I don't know there is a `*anaconda-mode*` buffer can provide such debug infomation.
