### ISSUE TITLE
python / autocompletion layers: anaconda auto-install failure keeps blocking python files editing

### ISSUE THREAD

**Issue by deb0ch** [syl20bnr/spacemacs#6566]
#### Description :octocat:
When using python and autocompletion layers out-of-the-box, anaconda automatic install fails and keeps showing errors when editing python files.

This makes python mode unusable as the error popups keep coming back.

#### Reproduction guide :beetle:
- Start Emacs
- open python file

*Observed behaviour:* :eyes: :broken_heart:
- error popup window keeps showing, even after closing it

*Expected behaviour:* :heart: :smile:
- error popup window should appear only once
- in a wonderful world there should be no errors at all

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.105.21
- Spacemacs branch: perso (rev. 7751d78)
- Graphic display: t
- Distribution: spacemacs
- Editing style: emacs
- Completion: helm
- Layers:
```elisp
(javascript
 (auto-completion :variables :disabled-for markdown org erc)
 (better-defaults :variables better-defaults-move-to-beginning-of-code-first nil)
 c-c  
 (colors :variables colors-enable-nyan-cat-progress-bar nil)
 common-lisp emacs-lisp git gtags helm markdown multiple-cursors org pdf-tools python ranger semantic
 (shell :variables shell-default-height 50 shell-default-position 'bottom)
 shell-scripts spacemacs-layouts syntax-checking version-control)
```

#### Backtrace :paw_prints:
```
Collecting anaconda_mode==0.1.2
  Using cached anaconda_mode-0.1.2-py2-none-any.whl
Collecting jedi>=0.9.0 (from anaconda_mode==0.1.2)
  Using cached jedi-0.9.0-py2.py3-none-any.whl
Collecting service-factory>=0.1.2 (from anaconda_mode==0.1.2)
Collecting six (from service-factory>=0.1.2->anaconda_mode==0.1.2)
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: jedi, six, service-factory, anaconda-mode
[31mException:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 335, in run
    prefix=options.prefix_path,
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 732, in install
    **kwargs
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 837, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 1039, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python2.7/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python2.7/distutils/command/install.py", line 289, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base[0m
[33mYou are using pip version 8.1.1, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.[0m
/usr/bin/python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
```

**Comment by deb0ch** [comment]
Omg, sorry for the noise.

I've had this issue for quite some time now and just realized that by some .spacemacs syncing accident I had the python layer declared twice and that was the cause of my problem...

Can't delete the issue, but I think it can be closed now.
