### ISSUE TITLE
Server Error: IOError(20, 'not a directory')

### ISSUE THREAD

**Issue by vitiral** [syl20bnr/spacemacs#6775]
I am running the most recent version of spacemacs. When I am editing a python file (with python-mode enabled) and I go to most places in the file, I get the error:

```
Server Error: IOError(20, 'not a directory')
```

I have debug mode enabled, and that is the only error I can see. When I open `*Messages*` there isn't anything but that error.

Does anyone know what is happening?

**Comment by TheBB** [comment]
Have a look in the anaconda-mode buffer.

**Comment by vitiral** [comment]
Hey @TheBB, here is what is in there:
```
anaconda_mode port 9000
127.0.0.1 - - [06/Aug/2016 09:36:04] ================================================================================
Traceback (most recent call last):
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/garrett/.local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "IOError(20, \'Not a directory\')"}}')
127.0.0.1 - - [06/Aug/2016 09:36:07] ================================================================================
Traceback (most recent call last):
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/garrett/.local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "IOError(20, \'Not a directory\')"}}')
127.0.0.1 - - [06/Aug/2016 09:36:08] ================================================================================
Traceback (most recent call last):
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/providers/basehttp.py", line 40, in do_POST
    status, response = self.server.service(data)
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/service.py", line 49, in __call__
    result = self.apply(method, args)
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/service.py", line 104, in apply
    server_error(args['id'], error)
  File "/home/garrett/.emacs.d/.cache/anaconda-mode/0.1.2/service_factory-0.1.2-py2.7.egg/service_factory/errors.py", line 92, in server_error
    six.raise_from(ServiceException(500, dumps(response)), error)
  File "/home/garrett/.local/lib/python2.7/site-packages/six.py", line 718, in raise_from
    raise value
ServiceException: (500, '{"jsonrpc": "2.0", "id": 1, "error": {"message": "Server error", "code": -32000, "data": "IOError(20, \'Not a directory\')"}}')
```

**Comment by TheBB** [comment]
Seems to originate from anaconda-mode so it's *probably* not our problem.

https://github.com/proofit404/anaconda-mode/

**Comment by vitiral** [comment]
opened this ticket over there, see reference above
