### ISSUE TITLE
when I open a python file, an error about flake8 comes out

### ISSUE THREAD

**Issue by GeraltCN** [syl20bnr/spacemacs#7534]
```
Can’t guess python-indent-offset, using defaults: 4
[yas] Reloaded everything (snippets will load just-in-time)....
Suspicious state from syntax checker python-flake8: Flycheck checker python-flake8 returned non-zero exit code 1, but its output contained no errors: Traceback (most recent call last):
  File "/Users/ducky/.pyenv/versions/3.5.2/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/main/application.py", line 316, in run
    self._run(argv)
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/main/application.py", line 300, in _run
    self.run_checks()
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/main/application.py", line 238, in run_checks
    self.file_checker_manager.run()
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/checker.py", line 343, in run
    self.run_serial()
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/checker.py", line 327, in run_serial
    checker.run_checks(self.results_queue, self.statistics_queue)
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/checker.py", line 573, in run_checks
    self.run_ast_checks()
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/checker.py", line 477, in run_ast_checks
    checker = self.run_check(plugin, tree=ast)
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/checker.py", line 457, in run_check
    return plugin['plugin'](**arguments)
  File "/Users/ducky/.pyenv/versions/3.5.2/lib/python3.5/site-packages/flake8/plugins/pyflakes.py", line 55, in __init__
    filename = utils.normalize_paths(filename)[0]
IndexError: list index out of range

Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!
```

Is that because of the flake8? How can I fix it, and if I removed syntax-checking layers. It will disappear.

**Comment by bmag** [comment]
> Try installing a more recent version of python-flake8, and please open a bug report if the issue persists in the latest release.  Thanks!

Please do that. The bug report (if needed) probably should be opened against [Flycheck](https://github.com/flycheck/flycheck/). I see there is already an open issue about it in [flake8's bug tracker](https://gitlab.com/pycqa/flake8/issues/235).

**Comment by otrenav** [comment]
@GeraltCN i know this is a little late, but in my case installing `radon` solved it.

**Comment by CDitzel** [comment]
> @GeraltCN i know this is a little late, but in my case installing `radon` solved it.

it does not

**Comment by wkcosmology** [comment]
I have a similar problem, where the checkers bring me annoying errors. In my case, it was the incompatibility between python2 and python3, so I add the following commands to my `~/.spacemacs`(you can get it though SPC+f+e+d in emacs)
```lisp
(custom-set-variables
 '(flycheck-python-flake8-executable "python3")
 '(flycheck-python-pycompile-executable "python3")
 '(flycheck-python-pylint-executable "python3"))
```
