### ISSUE TITLE
Anaconda-mode does not install properly

### ISSUE THREAD

**Issue by m3nthal** [syl20bnr/spacemacs#8412]
#### Description :octocat:
Anaconda-mode does not install properly.

#### Reproduction guide :beetle:
- `git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d`
- Start Emacs & wait packages to install
- Open a *.py file

*Observed behaviour:* :eyes: :broken_heart:
- anaconda-mode will be installed
- an error will happen during the installation (see the logs below)

*Expected behaviour:* :heart: :smile:
- anaconda-mode will be installed without errors

#### System Info :computer:
- OS: darwin
- Emacs: 25.1.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc0)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(python helm emacs-lisp)
```
- System configuration features: JPEG RSVG NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS NS MODULES

#### Backtrace :paw_prints:

During installation of anaconda-mode:
```
Searching for anaconda-mode==0.1.7
Reading https://pypi.python.org/simple/anaconda_mode/
Best match: anaconda-mode 0.1.7
Downloading https://pypi.python.org/packages/ed/cf/4aef9f7cd8ad80381fe7ddea88a58b74a5f881bd9479022a8cc80e82d5fd/anaconda_mode-0.1.7.tar.gz#md5=5c6e818b21e38350ceaae101f439c816
Processing anaconda_mode-0.1.7.tar.gz
Writing /var/folders/jg/n6g87c293tsdxlsjd3707_krj419bj/T/easy_install-Yr9VzO/anaconda_mode-0.1.7/setup.cfg
Running anaconda_mode-0.1.7/setup.py -q bdist_egg --dist-dir /var/folders/jg/n6g87c293tsdxlsjd3707_krj419bj/T/easy_install-Yr9VzO/anaconda_mode-0.1.7/egg-dist-tmp-Q5v4Bd
no previously-included directories found matching 'test'
creating /Users/usernmae/.emacs.d/.cache/anaconda-mode/0.1.7/anaconda_mode-0.1.7-py2.7.egg
Extracting anaconda_mode-0.1.7-py2.7.egg to /Users/usernmame/.emacs.d/.cache/anaconda-mode/0.1.7
Adding anaconda-mode 0.1.7 to easy-install.pth file

Installed /Users/usernmame/.emacs.d/.cache/anaconda-mode/0.1.7/anaconda_mode-0.1.7-py2.7.egg
Processing dependencies for anaconda-mode==0.1.7
Searching for service-factory>=0.1.5
Reading https://pypi.python.org/simple/service_factory/
Best match: service-factory 0.1.5
Downloading https://pypi.python.org/packages/d1/32/bacd539bc748af613082f8cf80c82311373a05bb4af2d43bc2ff5bbdcdcc/service_factory-0.1.5.tar.gz#md5=a0dd7745280da2284e8bdc2c03b853e4
Processing service_factory-0.1.5.tar.gz
Writing /var/folders/jg/n6g87c293tsdxlsjd3707_krj419bj/T/easy_install-isgfOe/service_factory-0.1.5/setup.cfg
Running service_factory-0.1.5/setup.py -q bdist_egg --dist-dir /var/folders/jg/n6g87c293tsdxlsjd3707_krj419bj/T/easy_install-isgfOe/service_factory-0.1.5/egg-dist-tmp-yNhr0V
creating /Users/usernmame/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py2.7.egg
Extracting service_factory-0.1.5-py2.7.egg to /Users/usernmame/.emacs.d/.cache/anaconda-mode/0.1.7
Adding service-factory 0.1.5 to easy-install.pth file

Installed /Users/usernmame/.emacs.d/.cache/anaconda-mode/0.1.7/service_factory-0.1.5-py2.7.egg
Processing dependencies for service-factory>=0.1.5
Finished processing dependencies for service-factory>=0.1.5
Searching for jedi>=0.10.0
Reading https://pypi.python.org/simple/jedi/
No local packages or download links found for jedi>=0.10.0
error: Could not find suitable distribution for Requirement.parse('jedi>=0.10.0') (--always-copy skips system and development eggs)
```

curl https://pypi.python.org/simple/jedi/
```
<!DOCTYPE html><html><head><title>Links for jedi</title></head><body><h1>Links for jedi</h1><a href="../../packages/06/f0/1d2a8462b322a200323f6c1fbd18a3d4047d2ed89a39b2f7f9a2b994a271/jedi-0.10.0-py2.py3-none-any.whl#md5=0502bae0a2909472a51c395e09612fa0" rel="internal">jedi-0.10.0-py2.py3-none-any.whl</a><br/>
<a href="../../packages/0e/da/fb440b4dabfcbebde9522213abf1b0a49ca0164ee75b8cb611cfe674dfda/jedi-0.6.0.tar.gz#md5=2e2d953bf8213e56478e5df886ea7c02" rel="internal">jedi-0.6.0.tar.gz</a><br/>
<a href="../../packages/33/99/655efb8398112be833d0705ff7cabfb6e896ca78b7eeac8571c78c8ca049/jedi-0.8.1.tar.gz#md5=0e4b205e05290b00ebabe19f351cddf7" rel="internal">jedi-0.8.1.tar.gz</a><br/>
<a href="../../packages/3a/37/629080b92b87bc65e3b1b4f5d539e22aa5dc45637eab0dd4b0cd8cf236c2/jedi-0.9.0.tar.gz#md5=2fee93d273622527ef8c97ac736e92bd" rel="internal">jedi-0.9.0.tar.gz</a><br/>
<a href="../../packages/41/86/63615d366ddb093b0844b7b6af6e2c20563493e7202a7b667c1ceb55e2a1/jedi-0.8.1-final0.tar.gz#md5=e4db996421a640d50f559587e805412b" rel="internal">jedi-0.8.1-final0.tar.gz</a><br/>
<a href="../../packages/4f/43/9b944b51e908c1e7af930dc4c68ce18be81562225eddcbee238ed1a83a88/jedi-0.5b5.tar.gz#md5=eaf183537b1fd2eb122b85c526dea729" rel="internal">jedi-0.5b5.tar.gz</a><br/>
<a href="../../packages/57/e8/5d5317f031361c4fc9da7b1efee06066e3e35fb55c13b97355ddfb7c27b0/jedi-0.8.0-final0.tar.gz#md5=25ba4ee6160c2de751bd00c7a4f32bff" rel="internal">jedi-0.8.0-final0.tar.gz</a><br/>
<a href="../../packages/a0/08/3856da5dbe7d821a66a52f7f54ff6797fa656f4f76e1ba51cad0870553c1/jedi-0.7.0.tar.gz#md5=fb4a452b6baa09ce7ced445e58625d25" rel="internal">jedi-0.7.0.tar.gz</a><br/>
<a href="../../packages/c4/59/e48a369168a84c8aef9127c227fc3b9f53bc9c528b24c2cda20487bc2deb/jedi-0.9.0-py2.py3-none-any.whl#md5=e9b14b854c2d4c2f8d9bdc4ad27a3d39" rel="internal">jedi-0.9.0-py2.py3-none-any.whl</a><br/>
<a href="../../packages/e6/2d/24bd4607257f464bad07d959011969ed0d15e7587cd66931eea4b2822135/jedi-0.5b3.tar.gz#md5=bcf0e066a317faf2e8b79fe4659ec54e" rel="internal">jedi-0.5b3.tar.gz</a><br/>
<a href="../../packages/e8/f4/5bcfb90718bd9205a41577def71bca76724b26dd9d277e08c259aa0d96c3/jedi-0.10.0-py2-none-any.whl#md5=c869b2cf52622dba44a7b2eb0e5cdd52" rel="internal">jedi-0.10.0-py2-none-any.whl</a><br/>
<a href="../../packages/f6/7d/e8f2619e139a749fc98a4300663d55655931cfc7dfd2b8a625cfa94b28db/jedi-0.5b4.tar.gz#md5=1ce28453b1f11df973c00b5f5f9b3da2" rel="internal">jedi-0.5b4.tar.gz</a><br/>
```

After opening *.py file:
```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/Users/username/.emacs.d/.cache/anaconda-mode/0.1.7/anaconda_mode-0.1.7-py2.7.egg/anaconda_mode.py", line 17, in <module>
    from jedi import Script, NotFoundError
ImportError: No module named jedi
```

pyenv versions
```
  system
* 2.7.13 (set by /Users/username/.pyenv/version)
  2.7.13/envs/robot2.7
  3.6.0
  3.6.0/envs/robot3.6
  jybot2.7
  jython-2.7.0
  jython-2.7.0/envs/jybot2.7
  robot2.7
  robot3.6
```

**Comment by rakyi** [comment]
Seems it is this upstream issue: https://github.com/proofit404/anaconda-mode/issues/225

**Comment by wudixiaotie** [comment]
Run command below to install jedi in anaconda_mode:
`PYTHONPATH=$HOME/.emacs.d/.cache/anaconda-mode/0.1.7 easy_install -d $HOME/.emacs.d/.cache/anaconda-mode/0.1.7 -S $HOME/.emacs.d/.cache/anaconda-mode/0.1.7 -a -Z jedi`

**Comment by bseng** [comment]
How can I fix it in windows?

**Comment by chenyangguang** [comment]
Well i use ubuntu16.04 system, emacs 25.1, and  fixed it just with the following easy way: 
`sudo easy_install jedi` 
it done.

**Comment by rramsden** [comment]
`pip install jedi` fixed the issue for me on OSX. I'm running Python installed via Homebrew.

**Comment by kwmiebach** [comment]
On debian 8 

```
sudo apt install python-pip
sudo pip install jedi
```

This installs jedi system-wide. For me it fixed the `Could not find ...jedi ...` problem in spacemacs

**Comment by Menq** [comment]
@wudixiaotie   thx

**Comment by Miciah** [comment]
The upstream issue was closed as fixed.  Is anyone still seeing problems, or can this issue be labeled as "Fixed upstream" and closed?
