### ISSUE TITLE
YCMD:can't complete

### ISSUE THREAD

**Issue by 41890819** [syl20bnr/spacemacs#8599]
#### Description :octocat:
<<YCMD cant' complete at all>>

#### Reproduction guide :beetle:
- Start Emacs
- mkdir a new dir for test, and type a .ycm_extra_flags file for ycmd
- reopen the emacs
- open a new c file, type #include <st
- then the problem occur

*Observed behaviour:* :eyes: :broken_heart:
<<ycmd can't complete the include file stdio and an error occur: 
RuntimeError: No completions found

**Comment by 41890819** [comment]
YCMD can't complete

**Comment by 41890819** [comment]
my .ycmd_extra_flags:
'-isystem',
'/usr/include',
'-isystem',
'/usr/local/include',


the ycmd-server:
2017-03-29 15:13:51,972 - DEBUG - Global extra conf not loaded or no function YcmCorePreload
serving on http://127.0.0.1:34589
2017-03-29 15:13:52,769 - INFO - Received event notification
2017-03-29 15:13:52,769 - DEBUG - Event name: BufferVisit
2017-03-29 15:13:52,786 - INFO - Received event notification
2017-03-29 15:13:52,786 - DEBUG - Event name: FileReadyToParse
2017-03-29 15:13:52,787 - INFO - Adding buffer identifiers for file: /home/jerry/work/c_code/a.c
2017-03-29 15:13:52,787 - INFO - /home/jerry/.emacs.d/layers/+tools/ycmd/global_conf.py: Getting flags for /home/jerry/work/c_code/a.c
2017-03-29 15:13:52,787 - INFO - a.c: Could not get compilation flags from db: could not find compile_commands.json
2017-03-29 15:13:52,787 - INFO - a.c: Found nearest .ycm_extra_flags at /home/jerry/work/c_code/.ycm_extra_flags
2017-03-29 15:13:52,787 - INFO - a.c: Extra flags = [
		'-isystem',
		'/usr/include',
		'-isystem',
		'/usr/local/include',
		'-I',
		'/home/jerry/work/oled_raypai/kernel/include'
]
2017-03-29 15:13:52,787 - INFO - a.c: Flags = [
		'-isystem',
		'/usr/include',
		'-isystem',
		'/usr/local/include',
		'-I',
		'/home/jerry/work/oled_raypai/kernel/include'
]
2017-03-29 15:14:00,646 - INFO - Received completion request
2017-03-29 15:14:00,647 - DEBUG - Using filetype completion: True
Traceback (most recent call last):
  File "/home/jerry/bin/ycmd/third_party/bottle/bottle.py", line 861, in _handle
    return route.call(**args)
  File "/home/jerry/bin/ycmd/third_party/bottle/bottle.py", line 1734, in wrapper
    rv = callback(*a, **ka)
  File "/home/jerry/bin/ycmd/ycmd/../ycmd/watchdog_plugin.py", line 108, in wrapper
    return callback( *args, **kwargs )
  File "/home/jerry/bin/ycmd/ycmd/../ycmd/hmac_plugin.py", line 70, in wrapper
    body = callback( *args, **kwargs )
  File "/home/jerry/bin/ycmd/ycmd/../ycmd/handlers.py", line 103, in GetCompletions
    .ComputeCandidates( request_data ) )
  File "/home/jerry/bin/ycmd/ycmd/../ycmd/completers/completer.py", line 217, in ComputeCandidates
    candidates = self._GetCandidatesFromSubclass( request_data )
  File "/home/jerry/bin/ycmd/ycmd/../ycmd/completers/completer.py", line 233, in _GetCandidatesFromSubclass
    raw_completions = self.ComputeCandidatesInner( request_data )
  File "/home/jerry/bin/ycmd/ycmd/../ycmd/completers/cpp/clang_completer.py", line 113, in ComputeCandidatesInner
    raise RuntimeError( NO_COMPLETIONS_MESSAGE )
RuntimeError: No completions found; errors in the file?

**Comment by 41890819** [comment]
there's an issue just same:https://github.com/abingham/emacs-ycmd/issues/166
this issue is just occured in spacemacs.   clean emacs or vim is just fine.

my Message buffer:REQUEST [error] Error (error) while connecting to http://127.0.0.1:44923/completions.
ycmd-server buffer:RuntimeError: No completions found; errors in the file?

**Comment by amosbird** [comment]
hmm, doesn't `.ycmd_extra_flags` file look like this :
```
-isystem=/usr/include
-isystem=/usr/local/include
```
