### ISSUE TITLE
pylookup-update fails

### ISSUE THREAD

**Issue by dxue2012** [syl20bnr/spacemacs#9272]
#### Description :octocat:
pylookup-update fails

#### Reproduction guide :beetle:
- Start Emacs
- `SPC : pylookup-update RET`

*Observed behaviour:* :eyes: :broken_heart:
Pylookup failed to update.

*Expected behaviour:* :heart: :smile:
Pylookup should be updated.

#### System Info :computer:
- OS: darwin
- Emacs: 24.5.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af14)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(markdown
 (auto-completion :variables auto-completion-return-key-behavior 'complete auto-completion-tab-key-behavior 'cycle auto-completion-enable-snippets-in-popup t auto-completion-enable-sort-by-usage t auto-completion-private-snippets-directory nil)
 better-defaults dash
 (elm :variables elm-format-on-save t)
 emacs-lisp git html python react
 (shell :variables shell-default-height 30 shell-default-position 'bottom)
 spell-checking
 (syntax-checking :variables syntax-checking-enable-tooltips nil)
 (typescript :variables typescript-fmt-tool 'typescript-formatter typescript-fmt-on-save t)
 javascript version-control wakatime ocaml osx yaml)
```

#### Backtrace :paw_prints:
```
Wait for a few seconds...
Fetching index from 'http://docs.python.org/genindex-all.html'
Traceback (most recent call last):
  File "/Users/me/.emacs.d/layers/ lang/python/local/pylookup/pylookup.py", line 324, in <module>
    update(opts.db, opts.url, opts.append)
  File "/Users/me/.emacs.d/layers/ lang/python/local/pylookup/pylookup.py", line 234, in update
    parser = IndexProcessor(writer, dirname(index_url))
  File "/Users/me/.emacs.d/layers/ lang/python/local/pylookup/pylookup.py", line 129, in __init__
    htmllib.HTMLParser.__init__( self, formatter.NullFormatter() )
TypeError: __init__() takes 1 positional argument but 2 were given
```

I am aware of [this issue](https://github.com/syl20bnr/spacemacs/issues/8637), which seems to have been resolved already by a patch last year, so I'm not sure why this is showing up again. For what it's worth, I'm using pyenv and have 3.6.2 set to global.

**Comment by dxue2012** [comment]
Never mind -- I spoke too soon. Apparently the patch made it to the develop branch but not master. I'll give the dev branch a try. Feel free to close this issue!

**Comment by dxue2012** [comment]
@mhePgts

Try using the dev branch of spacemacs.
