### ISSUE TITLE
Ruby layer usability: Document pry installation

### ISSUE THREAD

**Issue by mathpunk** [syl20bnr/spacemacs#9351]
I'm trying to use the Ruby layer. Eventually I figured out that I needed to set an rvm path variable in my .zshenv. However, I ran `gem install pry` from both my usual console and from the spacemacs shell, and when I attempt to start a Ruby repl, I get:

    irb: warn: can't alias context from irb_context.
    irb(main):001:0> LoadError: cannot load such file -- pry
	from /home/chiral/.emacs.d/elpa/robe-20170611.1755/lib/robe/sash/doc_for.rb:1:in `require'
	from /home/chiral/.emacs.d/elpa/robe-20170611.1755/lib/robe/sash/doc_for.rb:1:in `<top (required)>'
	from /home/chiral/.emacs.d/elpa/robe-20170611.1755/lib/robe/sash.rb:1:in `require'
	from /home/chiral/.emacs.d/elpa/robe-20170611.1755/lib/robe/sash.rb:1:in `<top (required)>'
	from /home/chiral/.emacs.d/elpa/robe-20170611.1755/lib/robe.rb:1:in `require'
	from /home/chiral/.emacs.d/elpa/robe-20170611.1755/lib/robe.rb:1:in `<top (required)>'
	from (irb):1:in `require'
	from (irb):1
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/cli/console.rb:18:in `run'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:396:in `console'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor.rb:369:in `dispatch'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:22:in `dispatch'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/vendor/thor/lib/thor/base.rb:444:in `start'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/cli.rb:13:in `start'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/exe/bundle:30:in `block in <top (required)>'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/lib/bundler/friendly_errors.rb:121:in `with_friendly_errors'
	from /home/chiral/.rvm/gems/ruby-2.4.0/gems/bundler-1.15.3/exe/bundle:22:in `<top (required)>'
	from /home/chiral/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `load'
	from /home/chiral/.rvm/gems/ruby-2.4.0/bin/bundle:22:in `<main>'
	from /home/chiral/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/chiral/.rvm/gems/ruby-2.4.0/bin/ruby_executable_hooks:15:in `<main>'

After that noise I have an irb prompt, so it is useable, but I don't know what path I need to add or what shell command I need to run in order to get pry up and running. Perhaps there could be additional instruction in the Ruby layer documentation to help one get up and running.

**Comment by mathpunk** [comment]
I've added `[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"` to .zshenv to make sure that rvm is in use, followed by `rvm use 2.4.0`. I deleted `elpa/robe` and then ran `gem install pry`. But, the same errors happen when I jack into the Ruby console with `, s i`.

**Comment by mathpunk** [comment]
Maybe my problem is I don't know the difference between a login shell and a not-login shell. That `rvm use 2.4.0` in .zshenv is evidently not correct, because upon restarting and entering the terminal I get

    RVM is not a function, selecting rubies with 'rvm use ...' will not work.

    You need to change your terminal emulator preferences to allow login shell.
    Sometimes it is required to use `/bin/bash --login` as the command.
    Please visit https://rvm.io/integration/gnome-terminal/ for an example.

**Comment by mathpunk** [comment]
Closing in favor of the better write-up in #9395.
