### ISSUE TITLE
Can not install 'anaconda-mode' server and cannot send buffer to repl in Python layer in Windows

### ISSUE THREAD

**Issue by chetnashah** [syl20bnr/spacemacs#9636]
#### Description :octocat:
Can not install 'anaconda-mode' server and cannot send buffer to repl in Python layer in Windows

#### Reproduction guide :beetle:
- Start Emacs
- Open a python file, and trying to open a repl with SPC m ' and sending buffer with SPC m s b

*Observed behaviour:* :eyes: :broken_heart:
Messages buffer shows following:
```
Can not install 'anaconda-mode' server
Sent: import math as math...
python-shell-send-file: Invalid format operation %%~
```

*Expected behaviour:* :heart: :smile:
Python repl should open normally and should be able to accept sent buffer
SPC m s b

#### System Info :computer:
- OS: windows-nt
- Emacs: 25.2.1
- Spacemacs: 0.200.9
- Spacemacs branch: master (rev. 8e1af145)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(sml latex helm markdown python javascript scheme clojure auto-completion common-lisp emacs-lisp rust org syntax-checking)
```
- System configuration features: XPM JPEG TIFF GIF PNG RSVG SOUND NOTIFY ACL GNUTLS LIBXML2 ZLIB TOOLKIT_SCROLL_BARS

#### Backtrace :paw_prints:
In the anaconda-mode buffer: following stacktrace is observed.
```
Searching for anaconda_mode==0.1.8
Reading https://pypi.python.org/simple/anaconda_mode/
Downloading https://pypi.python.org/packages/93/aa/35e6da163d1b2de4e8091da8273edb6c9947ba65111aa0274898fce17387/anaconda_mode-0.1.8.tar.gz#md5=91fee6b8ca69078e190484ed81e3f6f1
Traceback (most recent call last):
  File "<string>", line 8, in <module>
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line 2279, in main
    **kw
  File "c:\Python27\lib\distutils\core.py", line 151, in setup
    dist.run_commands()
  File "c:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line 411, in run
    self.easy_install(spec, not self.no_deps)
  File "c:\Python27\lib\site-packages\setuptools\command\easy_install.py", line 660, in easy_install
    not self.always_copy, self.local_index
  File "c:\Python27\lib\site-packages\setuptools\package_index.py", line 636, in fetch_distribution
    dist = find(requirement)
  File "c:\Python27\lib\site-packages\setuptools\package_index.py", line 617, in find
    dist.download_location = self.download(dist.location, tmpdir)
  File "c:\Python27\lib\site-packages\setuptools\package_index.py", line 566, in download
    found = self._download_url(scheme.group(1), spec, tmpdir)
  File "c:\Python27\lib\site-packages\setuptools\package_index.py", line 805, in _download_url
    return self._attempt_download(url, filename)
  File "c:\Python27\lib\site-packages\setuptools\package_index.py", line 811, in _attempt_download
    headers = self._download_to(url, filename)
  File "c:\Python27\lib\site-packages\setuptools\package_index.py", line 734, in _download_to
    self.check_hash(checker, filename, tfp)
  File "c:\Python27\lib\site-packages\setuptools\package_index.py", line 504, in check_hash
    "Validating %%s checksum for %s" % filename)
  File "c:\Python27\lib\site-packages\setuptools\package_index.py", line 285, in report
    msg = template % self.hash_name
TypeError: not enough arguments for format string
```

**Comment by CeleritasCelery** [comment]
you should report this upstream at anaconda-mode

**Comment by chetnashah** [comment]
No longer have windows installation, will check again and re-open if necessary
